### ISSUE TITLE
CC-license not recommend for software

### ISSUE THREAD

**Issue by rugk** [stolendata/totp#3]
As [you describe](https://github.com/stolendata/totp/blob/master/README.md#license) this software is licensed under a CC license. However CC licenses [should not be used](https://wiki.creativecommons.org/FAQ#Can_I_apply_a_Creative_Commons_license_to_software.3F) for software.
I would recommend to [choose another software license](http://choosealicense.com/) for this purpose.

More information about licenses on Github: https://help.github.com/articles/open-source-licensing/

**Comment by stolendata** [comment]
I'm aware of the CC licenses' terminology pandering towards the traditional forms of art. I'd gladly switch if there was another license that 1) requires attribution, 2) requires sharing alike, and 3) voids commercial use without the author's permission.

**Comment by rugk** [comment]
# Your requirements
1. This is required by nearly every license. E.g. by the GPL license ([source](https://www.gnu.org/licenses/gpl-faq.html#IWantCredit)).
2. The GPL license also contains a "thing" which is very similar - Copyleft. So by using a copyleft license like the GPL you can also accomplish this. More information: https://en.wikipedia.org/wiki/Copyleft
3. That's a problem if you want to use a free software license. That's why the license you choose (CC-BY-NC-SA) isn't a [free culture license](https://creativecommons.org/freeworks) - because of the "NonCommercial". For a more detailed explanation look at the previous link for the question "Why isn’t a license that restricts commercial use considered a free culture license?"
   Basically it's that you must not disallow any use of a free work.

# About non-commercial

So except 3 everything can be done with popular, free licenses.
Of course you can also try to find a license which [disallows commercial use](https://tldrlegal.com/search?reverse=true&cannot[]=52c0d009a1ddc9766c00000a), however this would make your work non-free and [incompatible with the GPL](https://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean).
If you still want to use them maybe the [Aladdin Free Public License](https://tldrlegal.com/license/aladdin-free-public-license) or the [Non-Profit Open Software License 3.0](https://tldrlegal.com/license/non-profit-open-software-license-3.0-%28nposl-3.0%29) may be something to do this. The latter one BTW allows commercial use, but only non-profit.

# Additional notes
- However I think a copyleft is enough to be quite sure it's not used in commercial use. Because even without the explicit prohibition of this a company could still sell the software - but (after paying - maybe a different value) they would have to provide the source\* code as well, which contains the right to redistribute, so if a person has the source once he is allowed to redistribute it for free under the terms of the GPL.
  More information: [FSF | Does the GPL allow me to sell copies of the program for money?](https://www.gnu.org/licenses/gpl-faq.html#DoesTheGPLAllowMoney) and the following questions
- Instead of using the pure GPL I would recommend you to use the AGPL as it is more suitable for web services, because it also requires to provide the source code if it's served with a web service. (which is mostly the case with a PHP script)
  More information: [Wikipedia](https://en.wikipedia.org/wiki/Affero_General_Public_License), [TLDRLegal](https://tldrlegal.com/license/gnu-affero-general-public-license-v3-%28agpl-3.0%29) and [FSF](https://www.gnu.org/licenses/why-affero-gpl.html)
- If you want to use the (A)GPL then please also note the changes between v2 and v3 which caused some discussions.
  More information: [Wikipedia](https://en.wikipedia.org/wiki/GNU_General_Public_License#Version_3), [FSF](https://www.gnu.org/licenses/rms-why-gplv3)

\* in an online service only if you use the AGLP like stated in the point below

# Disclaimer

Please note that I'm not a lawyer and although I'm trying to do my best I can't guarantee that all of my statements are completely correct. Please choose and check the license you want to use by yourself.

**Comment by stolendata** [comment]
To repeat the obvious and to underline the conclusion you already reached, the ingredient missing in all other popular license choices is number 3, which is very important to me. I believe in a software ecosystem that is commercially bidirectional in the same way it is non-commercially bidirectional. This is why I'm a CC user.
